#! /usr/bin/env ruby

require 'pg'
require 'date'

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(args)
    @command = args[0]
    parse_command
  end

  def parse_command
    if !@command || @command.downcase == 'help'
      @application.display_help
    elsif @command.downcase == 'list'
      @application.display_list
    elsif @command.downcase == 'add'
      @application.add_expense
    else
      puts "Sorry, #{@command} is not valid"
    end
  end
end

class ExpenseData
  def initialize
    @expense_db = PG.connect(dbname: 'project1')
  end

  HELP = <<~HELP
    Commands:\n
    add AMOUNT MEMO - record a new expense
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP

  def display_help
    puts "An expense recording system\n\n"
    puts HELP
  end

  def display_list
    @expenses = @expense_db.exec('SELECT * FROM expenses ORDER BY id')
    @expenses.each do |tuple|
      columns = [tuple['id'].rjust(3),
                 tuple['created_on'].rjust(10),
                 tuple['amount'].rjust(12),
                 tuple['memo']]

      puts columns.join(' | ')
    end
  end

  def add_expense(cost: ARGV[1], item: ARGV[2], date: ARGV[3])
    error_help = validate_add(cost: cost, item: item, date: date)

    if !error_help
      @expense_db.exec_params('INSERT INTO expenses(amount, memo, created_on)'\
        'VALUES ($1, $2, $3);', [cost, item, (date || Date.today.to_s)]).values
    else
      puts error_help
      puts @help
    end
  end

  def validate_date(date_str)
    Date.valid_date?(*date_str.split('-').map(&:to_i))
  rescue ArgumentError, NameError
    'The date you have entered is invalid.'
  else
    false
  end

  def validate_add(cost:, item:, date:)
    return 'Please enter a valid amount' unless cost.to_f > 0.0

    if !cost
      "You must specify an AMOUNT\n\n"
    elsif !item
      "You must specify a MEMO\n\n"
    elsif date
      validate_date(date)
    else
      false
    end
  end
end

CLI.new.run(ARGV)
